version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: "db2023_dev_mysql"
    command: --lower_case_table_names=1
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "idang"
      MYSQL_PASSWORD: "1948"
      MYSQL_ROOT_PASSWORD: "root"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "db2023_dev_phpmyadmin"
    restart: always
    ports:
      - 9111:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_USER: "idang"
      MYSQL_PASSWORD: "1948"
      MYSQL_ROOT_PASSWORD: "root"

  tomcat : 
    build: ./tomcatdeploy
    container_name: "db2023_tomcat_springboot"
    volumes : 
      - ./tomcatdeploy:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
  
  frontend:
    image: node:alpine
    environment:
      NODE_ENV: production
    volumes:
      - ./frontend/cinema-town/:/usr/src/app/
    command:  sh -c "cd /usr/src/app/ && yarn build  && yarn global add serve && serve -s build"
    expose: [3000]
    ports:
      - 80:3000


    

